In [41]:
df = pd.read_csv('./Covid19SidoInfState.csv')
df.stdDay = df.stdDay.str.replace('년 ','-')
df.stdDay = df.stdDay.str.replace('월 ','-')
df.stdDay = df.stdDay.str.replace('일','')
df.stdDay = df.stdDay.str.replace('[ ][0-9]*시', '')
df.stdDay = pd.to_datetime(df.stdDay)
df

,seq,stdDay,gubun,gubunCn,gubunEn,deathCnt,incDec,isolClearCnt,qurRate,defCnt,isolIngCnt,overFlowCnt,localOccCnt,createDt,updateDt
0,1,2020-03-01,합계,NaN,NaN,18.0,586.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-02 19:27:57.57,NaN
1,2,2020-03-01,서울,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-02 19:27:57.57,NaN
2,3,2020-03-01,부산,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-02 19:27:57.57,NaN
3,4,2020-03-01,대구,NaN,NaN,9.0,469.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-02 19:27:57.57,NaN
4,5,2020-03-01,인천,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-02 19:27:57.57,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9331,10092,2021-06-12,전남,全南,Jeollanam-do,15.0,4.0,1418.0,82.91,1546.0,113.0,NaN,4.0,2021-06-12 09:44:23.817,NaN
9332,10093,2021-06-12,경북,庆北,Gyeongsangbuk-do,86.0,5.0,4585.0,180.51,4806.0,135.0,NaN,5.0,2021-06-12 09:44:23.817,NaN
9333,10094,2021-06-12,경남,庆南,Gyeongsangnam-do,19.0,25.0,4689.0,149.49,5025.0,317.0,2.0,23.0,2021-06-12 09:44:23.817,NaN
9334,10095,2021-06-12,제주,济州,Jeju,1.0,5.0,1046.0,175.62,1178.0,131.0,NaN,5.0,2021-06-12 09:44:23.818,NaN
9335,10096,2021-06-12,검역,隔離區,Lazaretto,5.0,9.0,3768.0,-,3922.0,149.0,9.0,NaN,2021-06-12 09:44:23.818,NaN

In [43]:
corona = df

In [44]:
corona.loc[corona.gubun == '경남']

,seq,stdDay,gubun,gubunCn,gubunEn,deathCnt,incDec,isolClearCnt,qurRate,defCnt,isolIngCnt,overFlowCnt,localOccCnt,createDt,updateDt
16,17,2020-03-01,경남,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-02 19:27:57.57,NaN
35,36,2020-03-04,경남,NaN,NaN,NaN,1.0,NaN,1.9,65.0,NaN,NaN,NaN,2020-03-04 19:44:27.27,NaN
53,54,2020-03-05,경남,NaN,NaN,NaN,9.0,NaN,2.2,74.0,NaN,NaN,NaN,2020-03-05 15:29:39.39,NaN
71,72,2020-03-06,경남,NaN,NaN,NaN,3.0,NaN,2.3,77.0,NaN,NaN,NaN,2020-03-06 15:09:04.04,NaN
89,90,2020-03-07,경남,NaN,NaN,NaN,5.0,NaN,1.2,82.0,NaN,NaN,NaN,2020-03-07 15:29:59.59,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9257,9999,2021-06-08,경남,庆南,Gyeongsangnam-do,19.0,48.0,4614.0,146.01,4908.0,227.0,NaN,48.0,2021-06-08 09:44:36.244,NaN
9276,10037,2021-06-09,경남,庆南,Gyeongsangnam-do,19.0,39.0,4646.0,147.17,4947.0,282.0,NaN,39.0,2021-06-09 09:46:17.545,NaN
9295,10056,2021-06-10,경남,庆南,Gyeongsangnam-do,19.0,33.0,4662.0,148.16,4980.0,299.0,NaN,33.0,2021-06-10 09:39:59.535,NaN
9314,10075,2021-06-11,경남,庆南,Gyeongsangnam-do,19.0,20.0,4673.0,148.75,5000.0,308.0,NaN,20.0,2021-06-11 09:47:58.31,NaN
9333,10094,2021-06-12,경남,庆南,Gyeongsangnam-do,19.0,25.0,4689.0,149.49,5025.0,317.0,2.0,23.0,2021-06-12 09:44:23.817,NaN

In [47]:
train_df = pd.read_csv('./data/train.csv', encoding='utf-8')
test_df = pd.read_csv('./data/test.csv', encoding='utf-8')
sample = pd.read_csv('./data/sample_submission.csv', encoding='utf-8')

TRAIN_LENGTH = 1205

train_df['공휴일전후'] = 0
test_df['공휴일전후'] = 0

train_df['공휴일전후'][17] = 1
train_df['공휴일전후'][3] = 1
train_df['공휴일전후'][62] = 1
train_df['공휴일전후'][131] = 1
train_df['공휴일전후'][152] = 1
train_df['공휴일전후'][226] = 1
train_df['공휴일전후'][221] = 1
train_df['공휴일전후'][224] = 1
train_df['공휴일전후'][245] = 1
train_df['공휴일전후'][310] = 1 # 2
train_df['공휴일전후'][311] = 1
train_df['공휴일전후'][309] = 1
train_df['공휴일전후'][330] = 1
train_df['공휴일전후'][379] = 1
train_df['공휴일전후'][467] = 1
train_df['공휴일전후'][470] = 1
train_df['공휴일전후'][502] = 1
train_df['공휴일전후'][565] = 1
train_df['공휴일전후'][623] = 1
train_df['공휴일전후'][651] = 1
train_df['공휴일전후'][705] = 1
train_df['공휴일전후'][709] = 1
train_df['공휴일전후'][815] = 1
train_df['공휴일전후'][864] = 1
train_df['공휴일전후'][950] = 1
train_df['공휴일전후'][951] = 1
train_df['공휴일전후'][953] = 1
train_df['공휴일전후'][954] = 1
train_df['공휴일전후'][955] = 1
train_df['공휴일전후'][971] = 1 #2
train_df['공휴일전후'][1038] = 1
train_df['공휴일전후'][1099] = 1
train_df['공휴일전후'][1129] = 1
train_df['공휴일전후'][1187] = 1

test_df['공휴일전후'][10] = 1
test_df['공휴일전후'][20] = 1

df = pd.concat([train_df, test_df], axis=0).reset_index(drop=True)
df = pd.get_dummies(df, columns=['공휴일전후'])

y = train_df[['중식계', '석식계']]

df['출근'] = df['본사정원수'] - (df['본사휴가자수'] + df['본사출장자수'] + df['현본사소속재택근무자수'])
df['휴가비율'] = df['본사휴가자수'] / df['본사정원수']
df['출장비율'] = df['본사출장자수'] / df['본사정원수']
df['야근비율'] = df['본사시간외근무명령서승인건수'] / df['출근']
df['재택비율'] = df['현본사소속재택근무자수'] / df['본사정원수']

df.drop(columns=['본사정원수', '본사휴가자수', '본사출장자수', '현본사소속재택근무자수'], inplace=True)

df['year'] = df.일자.apply(lambda x : int(x[:4]))
df['month'] = df.일자.apply(lambda x : int(x[-5 :-3]))
df['day'] = df.일자.apply(lambda x : int(x[-2 :]))
df['week'] = df.day.apply(lambda x : x // 7)

# weather
temp = pd.read_csv('./data/temp.csv', encoding='utf-8')
df = pd.merge(df, temp, on='일자')

# corona
corona = pd.read_csv('./data/corona/Covid19SidoInfState.csv')
corona = corona.loc[corona.gubun == '경남']
corona.stdDay = corona.stdDay.str.replace('년 ', '-')
corona.stdDay = corona.stdDay.str.replace('월 ', '-')
corona.stdDay = corona.stdDay.str.replace('일', '')
corona.stdDay = corona.stdDay.str.replace('[ ][0-9]*시', '')
df.일자 = pd.to_datetime(df.일자)
corona.stdDay = pd.to_datetime(corona.stdDay)

corona.rename(columns={'stdDay' : '일자',
                       'defCnt' : '확진자수',
                       'incDec' : '전일대비증감',
                       'deathCnt' : '사망자수'},
              inplace=True)

si = SimpleImputer(fill_value=0)
for col in ['확진자수', '전일대비증감', '사망자수']:
    corona[col] = si.fit_transform(corona[col].values.reshape(-1, 1))

df = pd.merge(df, corona[['일자', '확진자수', '전일대비증감', '사망자수']], on='일자', how='left')
print(df)

FileNotFoundError: [Errno 2] No such file or directory: './data/train.csv'